#!/bin/sh
echo "Linking $1 to /tmp/ttyV0, generating dump files /tmp/in.txt and /tmp/out.txt"
socat $1 \
SYSTEM:'tee /tmp/in.txt |socat - "PTY,link=/tmp/ttyV0,raw,echo=0,waitslave,group-late=dialout,mode=660" |tee /tmp/out.txt'
